### ISSUE TITLE
Doesn't seem to work?

### ISSUE THREAD

**Issue by bfayers** [olavmrk/usb-libvirt-hotplug#1]
I have this in my 90-usb-libvirt-hotplug.rules
``ACTION=="add",SUBSYSTEM=="usb",DEVPATH=="/devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.0",RUN+="/opt/usb-libvirt-hotplug/usb-libvirt-hotplug.sh win10_ltsb"
``
It does not hotplug a device when I plug it in.

I manually made some xml:
`    <hostdev mode='subsystem' type='usb' managed='no'>
      <source>
        <address bus='3' device='27'/>
      </source>
      <alias name='hostdev2'/>
    </hostdev>`

and virsh attach-device-d that and it worked (however ofcourse the `device=` will change

Ideas?

**Comment by Axachi** [comment]
Did you ever get this working?

**Comment by bfayers** [comment]
I can't remember, and even if I did I definitely would not have the config for it anymore.
